In [1]:
import numpy as np

In [2]:
x = np.array([0.00001, 1, 2, 4, 10, 100])

In [3]:
x

array([1.e-05, 1.e+00, 2.e+00, 4.e+00, 1.e+01, 1.e+02])

In [9]:
np.exp(x)

array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 5.45981500e+01,
       2.20264658e+04, 2.68811714e+43])

In [13]:
# x는 오픈 시간 후, 랜덤하게 고객이 도착하는 시간을 의미함
np.random.seed(seed=1)
x = np.random.exponential(1, 10)
print(x)
print("*"*50)
print(np.mean(x), np.std(x))
entTime = np.cumsum(x)
print("*"*50)
print(entTime)

[5.39605837e-01 1.27412525e+00 1.14381359e-04 3.60012755e-01
 1.58709595e-01 9.68838717e-02 2.06114634e-01 4.23976482e-01
 5.05452542e-01 7.73959775e-01]
**************************************************
0.43389551257941206 0.35676829778886443
**************************************************
[0.53960584 1.81373109 1.81384547 2.17385823 2.33256782 2.42945169
 2.63556633 3.05954281 3.56499535 4.33895513]


In [15]:
u = np.random.random(1000)
print(u)
print(np.log(u))
lamda = 1
x = -lamda * np.log(u)
plt.hist(x, bins='auto')


[6.70350032e-01 4.30471783e-01 7.67788978e-01 5.36008495e-01
 3.98599266e-02 1.34793118e-01 1.93416399e-01 3.35663801e-01
 5.23129464e-02 6.05116781e-01 5.12061028e-01 6.17461012e-01
 4.32355595e-01 8.47700468e-01 4.54059056e-01 1.54035198e-02
 8.73068148e-01 6.56201548e-01 8.23003041e-01 9.51775693e-01
 5.09123835e-02 2.35071864e-01 6.33434435e-02 4.21657886e-01
 8.63829146e-01 8.16239827e-02 4.73111953e-01 1.25543110e-01
 7.72885602e-01 8.41422157e-01 4.32909382e-02 4.86440743e-01
 2.39411044e-01 9.52473782e-01 9.43892628e-01 6.13934002e-01
 9.73487397e-01 3.44861344e-01 8.97850718e-01 4.34594973e-01
 2.35814637e-01 9.40827963e-01 6.84218051e-01 6.49115853e-02
 8.70424857e-01 7.01380295e-01 6.04926873e-01 7.32374899e-01
 2.53439042e-01 6.00488955e-01 8.14619181e-01 5.41136603e-02
 1.30510671e-01 8.42445810e-01 6.18345869e-01 5.31287810e-01
 2.48290729e-01 2.95078575e-01 8.72686165e-01 4.21665935e-01
 6.44302556e-02 8.96985070e-01 2.03380833e-01 8.26227535e-01
 8.81770623e-01 4.867507

NameError: name 'plt' is not defined

In [17]:
c1 = np.array([10,100,1000])

In [19]:
log_c1 = np.log(c1)
print(log_c1)

[2.30258509 4.60517019 6.90775528]


In [83]:
first = np.random.normal(1,2,100)

In [103]:
np.random.exponential(4, 10)

array([3.40914456, 9.43143488, 1.70724898, 2.37341285, 7.62162119,
       3.43991857, 4.24518434, 1.30491181, 2.67359429, 3.88037382])

In [104]:
np.random.seed(seed = 1)
np.random.normal(1,10,5)

array([17.24345364, -5.11756414, -4.28171752, -9.72968622,  9.65407629])

In [105]:
np.random.normal(1,10,5)

array([-22.01538697,  18.44811764,  -6.61206901,   4.19039096,
        -1.49370375])

In [106]:
np.random.normal(1,10,5)

array([ 15.62107937, -19.60140709,  -2.22417204,  -2.84054355,
        12.33769442])

In [108]:
np.random.seed(seed = 1)
np.random.normal(1,10,5)

array([17.24345364, -5.11756414, -4.28171752, -9.72968622,  9.65407629])

In [151]:
np.random.seed(seed=1)
cookTime = np.random.normal(1, 0.2, 10)
cookTime

array([1.32486907, 0.87764872, 0.89436565, 0.78540628, 1.17308153,
       0.53969226, 1.34896235, 0.84775862, 1.06380782, 0.95012592])