In [1]:
'''0 번째 행에는 행렬의 차원 m, n, non-zero element 수를 추가한다.

SparseMatrix 자료구조

    행렬의 dimension m, n 을 입력받아 희소행렬 리스트를 [[m,n,0]]로 초기 설정한다.
    append method: [i, j, value] 형태의 리스트를 희소행렬 리스트에 추가한다.
    shape method: 희소행렬 dimension을 리턴한다.
    getValue method: i, j 행렬값을 리턴한다.
    print method: 희소행렬을 일반적 행렬 형태로 프린트한다. (0으로 구성된 m,n array를 만들고 i,j 행렬값을 업데이트한다.)

'''

class SparseMatrix:
    def __init__(self, m, n):
        self.list = [[m, n, 0]]
        self.m = m
        self.n = n
        
    def append(self, i, j, value):
        self.list.append([i, j, value])
        self.list[0][2] += 1
        
    def shape(self):
        return (self.m, self.n)
        
    def getValue(self, i, j):
        for k in range(1,len(self.list)):
            if self.list[k][0] == i and self.list[k][1] == j:
                return self.list[k][2]
        return  0
    
    def print(self):
        import numpy as np
        _tmp = np.zeros((self.m, self.n)) #m,n 크기의 0으로 채워진 행렬을 만듦.
        for i in range(1,len(self.list)):
            _tmp[self.list[i][0]-1][self.list[i][1]-1] = self.list[i][2]
        print(_tmp)

    '''두 희소행렬의 덧셈 알고리즘:
    덧셈 결과를 저장할 빈 희소행렬 c를 만든다.
    두 희소행렬 a, b의 unique 한 (i,j) 쌍의 집합을 u 라고 하자.
    u에서 원소를 하나씩 꺼내면서 a, b의 해당 위치 값을 구해 더한다.
    위에서 구한 값이 0이 아니면 c에 추가한다.
    '''
def add(a, b):
    c = SparseMatrix(a.list[0][0], a.list[0][1])
    d = set()
    if a.shape() != b.shape():
        print("차원이 달라 더할 수 없습니다.")
    else:
        for i in range(1, len(a.list)):
            d.add((a.list[i][0], a.list[i][1]))
        for j in range(1, len(b.list)):
            d.add((b.list[j][0], b.list[j][1]))
        for k in d:
            sum = a.getValue(k[0], k[1]) + b.getValue(k[0], k[1])
            if sum != 0:
                c.append(k[0], k[1], sum)
    return c
        

#두 희소행렬을 곱하는 함수 만들기
def mul(a, b):
    set_a = []
    set_b = []
    mul_S = SparseMatrix(a.m, b.n)
    _tmp = []
    if a.n != b.m:
        print("곱하기를 할 수 없습니다.")
    else:
        for i in range(1, len(a.list)):
            set_a.append([a.list[i][0], a.list[i][1]])
        for i in range(1, len(b.list)):
            set_b.append([b.list[i][0], b.list[i][1]])
            
        #0 1 2 3
        for s in range(len(set_a)):
            #1 2 3
            for k in range(1,a.n+1):
                if [set_a[s][1], k] in set_b:
                    if [set_a[s][0], k] in _tmp:
                        for j in mul_S.list:
                            if j[0] == set_a[s][0] and j[1] == k:
                                j[2] += a.getValue(set_a[s][0], set_a[s][1])*b.getValue(set_a[s][1], k)
                    else:
                        mul_S.append(set_a[s][0], k, a.getValue(set_a[s][0], set_a[s][1])*b.getValue(set_a[s][1], k))
                        _tmp.append([set_a[s][0], k])
    return mul_S
    
#희소행렬의 전치행렬 알고리즘 : 희소행렬의 행 [i,j,val] 을 [j, i, val] 로 바꿔 리턴한다.
def transpose2(a):
    t_a = SparseMatrix(a.n, a.m)
    for i in range(len(a.list)):
        if i == 0:
            t_a.list[0][2] = a.list[0][2]
        else:
            t_a.append(a.list[i][1], a.list[i][0], a.list[i][2])
    return t_a
            
a = SparseMatrix(3,3)
a.append(1,3,3)
a.append(2,1,1)
a.append(2,3,2)
a.append(3,2,1)

b = SparseMatrix(3,3)
b.append(1,1,1)
b.append(1,3,5)
b.append(2,2,2)
b.append(3,1,1)
b.append(3,2,1)


print(a.shape())

print(a.getValue(2,3))
a.print()
b.print()

d = add(a,b)

mul(a,b).print()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

(3, 3)
2
[[0. 0. 3.]
 [1. 0. 2.]
 [0. 1. 0.]]
[[1. 0. 5.]
 [0. 2. 0.]
 [1. 1. 0.]]
[[3. 3. 0.]
 [3. 2. 5.]
 [0. 2. 0.]]
